hugoblox:
  schema: "2.0"
  identity:
    name: Avi Vajpeyi
    type: person
    tagline: Postdoctoral Research Fellow | University of Auckland
    description: |-
      I work on Bayesian inference for gravitational-wave astrophysics.
      My research spans LVK parameter estimation and Bayesian noise modeling for LISA.
  theme:
    mode: system
    pack: default
    colors:
      primary: orange
      secondary: ""
      neutral: ""
  typography:
    font: sans
    size: md
  layout:
    radius: md
    spacing: comfortable
    avatar_shape: circle
  header:
    enable: true
    style: navbar
    sticky: true
    align: center
    search: true
    theme_toggle: false
  footer:
    style: minimal
    language_switcher: true
  copyright:
    notice: Â© {year} {name}
  content:
    math:
      enable: false
    toc:
      enable: true
    reading_time:
      enable: false
  search:
    enable: true
  repository:
    enable: true
    url: "https://github.com/avivajpeyi/website_builder"
    branch: main
    content_dir: content
  analytics:
    google:
      measurement_id: "G-736274XEVL"
